### PR TITLE
Add a new certificate

### PR DESCRIPTION
**Pull request by kundra28**
adding certificate config for first drive

### CODE REVIEW

**Comment by shridarpatil** [comment]
You need to add certificate also. Adding just the type is not enough it will not generate the certificate.

**Comment by shridarpatil** [comment]
I have sent a pr https://github.com/fossunited/robinhood/pull/29. You can dynamically create an n number for certificates which will automatically generate and trigger an email to robin

**Comment by kundra28** [comment]
Hi Sridhar,
All the certificates have a png image associated with them. I wasn't sure
how to create the same for the new certificate.
Please advise.

**Comment by shridarpatil** [comment]
You need to get it done from designer or if you can design it by yourself.

**Comment by shridarpatil** [comment]
By when you need the png?

**Comment by shridarpatil** [comment]
If you give me the content I can ask our designer to design it for you.

**Comment by kundra28** [comment]
Attaching the logo for the *CADET* badge along. Please let me know if
anything else is required.

**Comment by shridarpatil** [comment]
You need to also add cadet certificate in download certificate api

**Pull request merged**
